### ISSUE TITLE
载入后所有消息都被拦截

### ISSUE THREAD

**Issue by ElainaFanBoy** [mute23-code/nonebot_plugin_githubcard#1]
日志里显示matcher by这个插件，包括其他消息都被本插件拦截了

**Comment by KomoriDev** [comment]
优先级问题（？）有修复吗

**Comment by ElainaFanBoy** [comment]
> 优先级问题（？）有修复吗

我fork了一份改了改，我这边倒是能用了

**Comment by KomoriDev** [comment]
> > 优先级问题（？）有修复吗
> 
> 我fork了一份改了改，我这边倒是能用了

彳亍，有空完善下
